# Archivo de configuración para la documentación de comercio exterior,
# con un tema minimalista, oscuro y fácil de leer

site_name: "Documentación de Comercio Exterior"
site_description: "Guía práctica para exportar ácido sulfúrico desde México a Guatemala."
site_author: "Equipo de Comercio Exterior"
site_url: "https://github.com/neestoralvz/comercio_exterior"
repo_url: "https://github.com/neestoralvz/comercio_exterior"
repo_name: "neestoralvz/comercio_exterior"

# Estructura de la navegación (nav) para incluir todos los archivos del proyecto
nav:
  - Inicio: index.md
  - Precios y Pagos:
      - Precios: 01_precios_y_pagos/precios.md
      - Términos de Pago: 01_precios_y_pagos/terminos_de_pago.md
  - Normativas y Regulaciones:
      - México: 02_normativas_y_regulaciones/mexico.md
      - Guatemala: 02_normativas_y_regulaciones/guatemala.md
  - Incoterms:
      - Seleccionados: 03_incoterms/incoterms_seleccionados.md
  - Requisitos Legales y Aduaneros:
      - Documentación de Exportación: 04_requisitos_legales_y_aduaneros/documentacion_exportacion.md
      - Documentación de Importación: 04_requisitos_legales_y_aduaneros/documentacion_importacion.md
      - Agentes Aduanales y Contactos: 04_requisitos_legales_y_aduaneros/agentes_aduanales_contactos.md
      - Permisos Especiales: 04_requisitos_legales_y_aduaneros/permisos_especiales.md
  - Entrega en Suchiate:
      - Logística con Pipas: 05_entrega_suchiate/logistica_pipas.md
      - Seguridad en Traslado: 05_entrega_suchiate/seguridad_traslado.md
  - Formalidades de Frontera:
      - Exportación en México: 06_formalidades_frontera/exportacion_mexico.md
      - Importación en Guatemala: 06_formalidades_frontera/importacion_guatemala.md

# Directorio donde se encuentran los archivos de la documentación
docs_dir: "docs"

# Control estricto de enlaces y configuraciones
strict: true
use_directory_urls: true

# Tema minimalista y oscuro basado en mkdocs-material
theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    - scheme: slate
      primary: "blue"
      accent: "blue"
  # Puedes desactivar la paleta clara si quieres forzar modo oscuro:
  # palette:
  #   - scheme: slate
  #     primary: "blue"
  #     accent: "blue"

# Extensiones de Markdown recomendadas
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
      separator: "_"
  - footnotes
  - tables
  - attr_list

# Plugins (ajusta según tus necesidades)
plugins:
  - search
  # - mkdocs-git-revision-date-localized-plugin
  # - mkdocs-pdf-export-plugin

# Archivos adicionales (CSS/JS) opcionales para personalizar
extra_css: []
extra_javascript: []

# Metadatos extra (opcionales)
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/neestoralvz/comercio_exterior"
  contact_email: "contacto@tuempresa.com"
  version: "1.0.0"
